org: tvqqq
app: diemtamsuky-api
service: diemtamsuky-api
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x
  region: ap-southeast-1
  timeout: 10
  httpApi:
    cors: true
  environment:
    SENTRY_DSN: ${param:SENTRY_DSN}
    NODE_ENV: ${param:NODE_ENV}
    OA_TOKEN: ${param:OA_TOKEN}
    MONGODB_URL: ${param:MONGODB_URL}
    SLACK_WEBHOOK_URL: ${param:SLACK_WEBHOOK_URL}
    AUTH0_ISSUER_BASE_URL: ${param:AUTH0_ISSUER_BASE_URL}
    ZALO_ADMIN_FOLLOWER_ID: ${param:ZALO_ADMIN_FOLLOWER_ID}
    CLOUDINARY_MENU_BASE_URL: ${param:CLOUDINARY_MENU_BASE_URL}
    TOKEN_SECRET: ${param:TOKEN_SECRET}

functions:
  api:
    handler: handler.serverless
    events:
      - httpApi: "*"
